LYNDVHAR-NOBILITY/Lyndvhar

code/modules/clothing/rogueclothes/armor.dm
code/modules/clothing/rogueclothes/feet.dm
code/modules/clothing/rogueclothes/gloves.dm
code/modules/clothing/rogueclothes/hats.dm
code/modules/clothing/rogueclothes/mask.dm
code/modules/clothing/rogueclothes/neck.dm
code/modules/clothing/rogueclothes/pants.dm
code/modules/clothing/rogueclothes/wrists.dm

Tweaks armor values and crit protection flags in order to form coherent niches within each weight category. Crit protection is made generally more scarce. Also adds proper mammon values to armors that were lacking it before.
Work in progress, need to finish some categories and remove blacksteel equipment from jobs that get it roundstart.
Choice of armor becomes more important with more factors to consider, makes specialized weaponry more important rather than just hitting armor with whatever deals more damage until it breaks.

Armor Rebalance, First Pass

---

code/modules/mob/living/carbon/human/species_types/roguetown/goblin/goblinp.dm

This changes the goblin name into being hobgoblins to differentiate them from their uncivilized counterparts, also adds the "Cave Dweller" and "Ocean Kissed" skin tones and removed very similar skin tones
It makes the goblins just a slightly more inmersive thing

Changes to Goblin.dm

---

code/datums/keybinding/client.dm
code/datums/world_topic.dm
code/modules/admin/admin_verbs.dm
code/modules/admin/chat_commands.dm
code/modules/admin/holder2.dm
code/modules/admin/verbs/adminhelp.dm
code/modules/client/client_procs.dm
code/modules/client/verbs/who.dm

Various Things And Removals To kill adminhelp and adminwho
Removes Adminwho and Adminhelp, the former by removing it entirely as it was still showing up when removing the verb in admin_verbs, it removes the latter by simply making the button say that you should go to the discord
Big man told me to do it

Kills AdminWho and AdminHelp

---

code/modules/jobs/job_types/roguetown/Inquisition/inquisitor.dm
code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/sister.dm
code/modules/jobs/job_types/roguetown/adventurer/bandit.dm
code/modules/jobs/job_types/roguetown/adventurer/wretch.dm
code/modules/jobs/job_types/roguetown/church/acolyte.dm
code/modules/jobs/job_types/roguetown/church/priest.dm
code/modules/jobs/job_types/roguetown/church/templar.dm
code/modules/jobs/job_types/roguetown/courtier/councillor.dm
code/modules/jobs/job_types/roguetown/courtier/jester.dm
code/modules/jobs/job_types/roguetown/courtier/magician.dm
code/modules/jobs/job_types/roguetown/garrison/sergeant.dm
code/modules/jobs/job_types/roguetown/garrison/townguard.dm
code/modules/jobs/job_types/roguetown/garrison/veteran.dm
code/modules/jobs/job_types/roguetown/garrison/villagechief.dm
code/modules/jobs/job_types/roguetown/mercenaries/mercenary.dm
code/modules/jobs/job_types/roguetown/nobility/captain.dm
code/modules/jobs/job_types/roguetown/nobility/hand.dm
code/modules/jobs/job_types/roguetown/nobility/knight.dm
code/modules/jobs/job_types/roguetown/nobility/lady.dm
code/modules/jobs/job_types/roguetown/nobility/lord.dm
code/modules/jobs/job_types/roguetown/nobility/marshal.dm
code/modules/jobs/job_types/roguetown/nobility/steward.dm
code/modules/jobs/job_types/roguetown/peasants/knavewench.dm
code/modules/jobs/job_types/roguetown/yeomen/archivist.dm
code/modules/jobs/job_types/roguetown/yeomen/nightmaster.dm
code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
code/modules/jobs/job_types/roguetown/youngfolk/squire.dm

Some of these were really stupid and needed changed. PlayerQuality itself should not be such a heavy measure in to how we stop people from playing jobs beyond as punishment measures. Anybody and their mother can just farm PQ, so it shouldn't be used as such a measurement.
This server is not going to be doing things the Vanderlin way (making PQ measurements insanely high) nor any other way beyond what is presented here.
So here's how this is going to go-
Important jobs are going to be 5PQ. That goes for the Viscount, blah blah.
Jobs below this are going to be 4.
And the others below are 3, 2, 1, 0, etc. There's no reason for it to be as restrictive as it was.
Makes me happier and brings in line with our rules, regulations, etc.

The big PQ lessening

---

code/datums/gods/patrons/inhumen_pantheon.dm
code/modules/cargo/packsrogue/tools.dm
code/modules/roguetown/roguecrafting/alchemy/reagents.dm
code/modules/roguetown/roguejobs/alchemist/container.dm
goon/browserassets/css/browserOutput.css

Adds a leech repellent potion to the Goldface. It is a vile concoction that makes your blood taste equally vile to any leeches who would dare feed on your blood. First drinking it causes you to vomit depending on your Constitution, and drinking too much makes you aggressively puke it all out.
Also adds the leech immune trait to Zizo worshippers by default, since they were the only Inhumen Worshippers without a bonus trait.
Adds a layer of preparation for swamp expeditions. Since these can only be acquired through the Merchant, it also encourages Adventurers to seek out his patronage in doing so.

Lecherine/Leech Repellent

---

code/modules/jobs/job_types/roguetown/garrison/bogguard.dm

Gives wardens a leather helmet.
Swaps their skill levels around to make them more focused towards using axes, bows and knives instead of polearms, swords and shields.

WardenFixes2

---

code/game/objects/items/rogueweapons/melee/special.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm

adds steel dusters to the Barbarian's weapon loadout. 
also fixes a bug that stopped them from spawning in on the wretch berserker and barbarian.
Another thing for barbarians to punch stuff with.

Gives barbarian Another weapon option on spawn

---

modular_azurepeak/virtues/combat.dm

Comments out Devotee from being able to be picked as a virtue, like Latent Arcyne.
Devotee has been used as a way to get free healing miracles. I thought it would be neat to have to show people with closer connections to the Pantheon, but it's not really being used as anything more than this. If anyone can come up with a more interesting form of Devotee, go ahead and do it- but this is how it's going to be dealt with for now.

Eliminates being very faithful

---

code/__HELPERS/unsorted.dm
code/_onclick/drag_drop.dm
code/_onclick/other_mobs.dm
code/game/objects/items/rogueweapons/intents.dm
code/game/objects/items/rogueweapons/melee/axes.dm
code/game/turfs/closed/_closed.dm
code/game/world.dm
code/modules/admin/blacklist.dm
code/modules/clothing/rogueclothes/neck.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/atgervi.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/carbon/human/human_helpers.dm
code/modules/mob/living/carbon/human/species.dm
code/modules/mob/living/carbon/life.dm
code/modules/mob/living/grabbing.dm
code/modules/mob/living/living.dm
code/modules/mob/living/roguetownprocs.dm
code/modules/mob/living/stats.dm
code/modules/surgery/surgery_helpers.dm

A couple of assorted changes to combat, as well as a bugfix.
- Unarmed attacks, such as grabs and punches, now have their parry/dodge chance capped at 95% instead of 90%. This is to represent the difficulty in hitting someone with your bare hands when otherwise hopelessly outmatched in melee. It also makes 'grab gambling', banking on the minimum 10% chance to land a grab, less powerful.
- All simplemob attacks count as being unarmed for the above change.
- Unarmed strikes can now benefit from having a higher speed than the opponent, reducing their parry/dodge chance, as well as from having higher strenght than the opponent, increasing their parry drain. This is the equivalent of these strikes having the properties of both swift and heavy weapons combined. Simplemobs do not benefit from …

2 AM Combat Dev [TESTMERGE FIRST]

---

code/modules/roguetown/roguemachine/merchant.dm

Unlocks all categories of goods on the Goldface by default. Meant to be reverted or reworked later.
The server hasn't yet reached a stable population and as consequence, merchant characters are very rare. Unlocking these categories, in this case, by default allows makes the Goldface more useful to the residents of the town and allows for more gimmicks.

Goldface Contigency Change

---

code/game/area/roguetownareas.dm
code/modules/antagonists/roguetown/villain/zombie/zombie.dm
code/modules/mob/living/carbon/human/npc/deadite.dm

Adds Deadites to a few areas, for ambushes. Keep in mind those are very simple no-armor Deadite NPCs. Also lets them attempt a bite every 10 seconds + gives deadite NPC mobs a chance to say something before turning, Also makes sure NPC deadites don't clutter the global antag list.
It adds ever so slightly more variety to ambushes in the forest, as the pop is a bit low at the moment you wouldn't see deadites normally otherwise.

This adds deadite ambushes to serveral areas

---

code/modules/surgery/_surgery_step.dm

Failing surgery intentionally tells you to swap to weak intent if its unintentional.
I spent 15 minutes after cloning the code base trying to figure out why I kept crit failing surgery just to find out you need to weak intent for it to work after scouring the code. While I don't quite think this is too crazy of a concept to allow malpractice for both fun and profit the vast majority of uses of this will just confuse them since they forgot or you've never interacted with this codebase like me and are confused at why you're constantly failing.

Intentional surgery failures tell you to swap to weak intent.

---

strings/german_replacement.json

Grenzer accents now swap W's for V's. This includes german full swaps for reference.
Grenzer accents will also now swap Yea for 'Ja'.
This helps tell people you have an accent rather than being a doofus throwing random german words at people.
The Yea change is because I found it kinda dumb that you would swap 'Yes' but not Yea???

Grenz accent changes.

---

strings/german_replacement.json

Beer->Bier
Wine was removed because it goes to 'vein' with the W autoreplacement.
Why is Beer not autoreplaced?
The Wein one has to go if we're keeping W's swapping else everyone is gonna be confused about you asking for veins.

Removes Wine from Grenzer autoreplacement and replaces it with a Beer autoreplacement.

---

code/modules/cargo/packsrogue/Brigand.dm
code/modules/cargo/packsrogue/Iconoclast.dm
code/modules/cargo/packsrogue/Knight.dm
code/modules/cargo/packsrogue/Sellsword.dm
code/modules/cargo/packsrogue/armor.dm
code/modules/roguetown/roguemachine/merchant.dm

Adjusts favor costs of equipment in the HOARDMASTER, as well as hopefully fixes the Wardrobe category of the GOLDFACE.
I'm genuinely shocked how inexpensive and cheap shit like BLACKSTEEL FULL PLATE is in the HOARDMASTER for bandits. Also uh.. for some reason.. the wardrobe was listed as "wardobre" in the GOLDFACE which is why it wasnt pulling from the WARDROBE define for clothes.
This fixes all of that. The balancejak here is rudimentary for the prices, though. (I also adjusted armor pricing values in the GOLDFACE tremendously because im an asshole).

Bandit Favor Cost Adjustments + Hopefully fixes GOLDFACE issues

---

code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/psydoniantemplar.dm

Psydon isn't real and can't hurt you (but his goons certainly are and definitely can)
This removes Adjucator's miracles since psydon isn't even real. I gave them a bit extra stats (1 str and 1 con) to compensate for the removal of their miracles.
Psydon isn't real lorewise so he shouldn't be able to grant you miracles in the first place.

Adjucators no longer get holy magic

---

code/modules/cargo/packsrogue/Brigand.dm
code/modules/cargo/packsrogue/Knave.dm
code/modules/cargo/packsrogue/Knight.dm
code/modules/cargo/packsrogue/Sellsword.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/hedgeknight.dm
code/modules/roguetown/roguemachine/hoardmaster.dm
lyndvhar.dme

First off the most important thing here is I did bandit housecleaning for Sellsword which had a ton of stuff be cheaper because Bowl didn't touch it. This also adds a few options for a few of the banditos in terms of weaponry alongside entirely disabling Blacksteel for them to buy.
This also readds Hedge Knight as a job for Bandits. There's only one and they're the main 'fighty' guy. They have great skills, heavy armor training, and statlines for combat in comparison to most but their intelligence is *absolutely* trash. Here is their spawn loadout and stats with virtuous. They are limited to 1. 
Their gear options range from medium to heavy armor. Its very expensive for them to actually get money since they have no utility skills compared to even the other combat jobs and their gear is …

Bandit Favor House Cleaning, Readds Hedge Knight, Adds a few options to certain banditos.

---

modular_azurepeak/statpacks/agile.dm
modular_azurepeak/statpacks/physical.dm

Bowl likes saying balancejak so I MJP claim balancjak.
Anyways this does some touches to certain statpacks.
- Swift now removes 2 perception
- Hulking removes a perception and gives you an endurance rather than removing one.
- Muscular drops an int on you.
Swift removes perception from you to balance out the insane gain that is 3 speed. Losing 2 con isn't much of a downside in my experience with the job since 90% of combat jobs (and honestly noncombat jobs in general should probably always swift) gain 1-2 con anyway and I've been one click delimbed with 15 con several times. Removing 2 per means its harder for them to hit gaps in armored opponents if you want to speedmaxx.
Hulking sucks. There's no way to get around it. Losing an endurance and 2 speed is just brutal since anyone with …

Statpack balancjak

---

code/game/objects/items/rogueweapons/melee/special.dm

Steel Knuckles (and Eoran knuckles but those are not obtainable anywhere seemingly.) are now 2x1 size.
Makes sense to me steel knuckles would be 2x1 instead of 2x2.

Steel Knuckles are 2x1

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/forlorn.dm

Forvhepial Sharpshooter now is a javelin thrower from a bow class. Their stats are unchanged.
- Expert bows removed and replaced with journeyman knives/polearms.
- Bow removed and replaced with iron javelins.
- You now get a messer on spawn as well.
Adds a class that actually uses javelins so people can try them out.

Reclasses Forvhepial sharpshooter into a Javelin Thrower

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm

Okay. So I've rebracketed the SP of Spellblade/Spellsinger/Mage.
Instead of 2/4/5 it is now 4/5/7.
Spellblade had comically bad SP and made me realize outlander mage also had pretty bad SP. This spread should more clearly show off the fact these jobs are skilled at magic rather than just having *one actual spell* in most cases from the SP costs for the lower end and maybe one and a half at the higher end since they're 3 subclasses capped to a max of 2.

Outlander Spell Points rebracketed

---

code/modules/admin/whitelist.dm

Actually use ~/config/whitelist.txt as config.txt says, instead of the nowhere-mentioned ~/config/roguetown/wl_mat.txt
Fixes Whitelist System

Fix: Load whitelist from correct file
