code/modules/mob/living/carbon/human/species_types/furry/akula.dm

showing runner how to make pull requests from a branch

---

modular_azurepeak/virtues/combat.dm

Comments out arcane potential
Magic should be rarer

Kills Arcane Potential

---

config/admin_nicknames.json
config/admin_ranks.txt
config/admins.txt
config/config.txt
config/game_options.txt
config/motd.txt
config/whitelist.txt

Reverts bowlofcereal/Lyndvhar#16

Revert "Revert "admin""

---

config/admin_nicknames.json
config/admin_ranks.txt
config/admins.txt
config/config.txt
config/game_options.txt
config/motd.txt
config/whitelist.txt

STupidAdminFixFinalTry

---

_maps/map_files/dun_manor/azure_forest.dmm
_maps/map_files/dun_manor/dun_manor.dmm
code/game/area/roguetownareas.dm
code/game/objects/structures/fluff.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/aasimar.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/halforc.dm

Removes a few flavor text thingies about Azure Peak really.
This isn't Azure Peak.

Removes some mentions of Azure Peak

---

code/game/gamemodes/dynamic/dynamic.dm
code/game/gamemodes/extended/extended.dm
code/game/gamemodes/game_mode.dm

Non inmersive messaging kill
Should not shout like it's the normal space station in a rogue server

Tentative fix for TG announce

---

code/modules/jobs/job_types/roguetown/garrison/townguard.dm
code/modules/jobs/job_types/roguetown/youngfolk/squire.dm

Bowl got very angry and started yelling and it was scary. So I fixed the thing he complained about.
Because bowl said so.

Fixes Garrison Slots

---

.gitignore

Remove config directory from gitignore

---

code/modules/jobs/job_types/roguetown/youngfolk/prince.dm

Renames Prince/Princess to Heir/Heiress. Probably going to break something at first but I'll fix it.
Bowl wants it.

Renames Prince/Princess

---

code/controllers/subsystem/particle_weather.dm
code/datums/sexcon.dm
code/game/gamemodes/game_mode.dm
code/game/objects/structures/maneater.dm
code/modules/admin/IsBanned.dm
modular/Neu_Food/code/raw/NeuFood_processed.dm
modular_azurepeak/virtues/utility.dm

this is the correct 515 syntax
syntax

Some 515 syntax proc-refing

---

code/datums/gods/faiths/divine_pantheon.dm
code/datums/gods/faiths/inhumen_pantheon.dm
code/datums/gods/faiths/old_god.dm
code/datums/gods/patrons/divine_pantheon.dm
code/datums/gods/patrons/inhumen_pantheon.dm
code/datums/gods/patrons/old_god.dm

Updates all of the PANTHEON to be in line with the LYNDVHAR lore. Also updates the INHUMEN, changing them to be the ARCHDAEMONs. As well as changing "Old God" to Foreign Gods (for future patrons of other realms) and making Psydon his own god, worshipped by another society entirely.
Brings it in line with my lore and makes it more descriptive and interesting.

The Patron Gods and Daemons of Beowricke

---

code/datums/gods/patrons/divine_pantheon.dm

read title
forgot to update poor xylix lore. free my boy

i forgot xylix

---

.github/workflows/label_merge_conflicts.yml

Merge conflict action fix probs

---

code/modules/jobs/job_types/roguetown/Inquisition/puritan.dm

removing my placeholder desc now that the psydon lore is done
because i am just that cool

Redoing inquis desc

---

code/modules/jobs/job_types/roguetown/courtier/butler.dm
code/modules/jobs/job_types/roguetown/courtier/magician.dm
code/modules/jobs/job_types/roguetown/courtier/physician.dm
code/modules/jobs/job_types/roguetown/garrison/veteran.dm
code/modules/jobs/job_types/roguetown/nobility/captain.dm
code/modules/jobs/job_types/roguetown/nobility/knight.dm
code/modules/jobs/job_types/roguetown/nobility/lady.dm
code/modules/jobs/job_types/roguetown/nobility/lord.dm
code/modules/jobs/job_types/roguetown/peasants/cook.dm
code/modules/jobs/job_types/roguetown/yeomen/archivist.dm
code/modules/jobs/job_types/roguetown/yeomen/artificer.dm
code/modules/jobs/job_types/roguetown/yeomen/barkeep.dm
code/modules/jobs/job_types/roguetown/yeomen/tailor.dm
code/modules/jobs/job_types/roguetown/youngfolk/apothecary.dm
code/modules/jobs/job_types/roguetown/youngfolk/churchling.dm
code/modules/jobs/job_types/roguetown/youngfolk/clerk.dm
code/modules/jobs/job_types/roguetown/youngfolk/mage_apprentice.dm
code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
code/modules/jobs/job_types/roguetown/youngfolk/servant.dm
code/modules/jobs/job_types/roguetown/youngfolk/shophand.dm
code/modules/jobs/job_types/roguetown/youngfolk/smith_apprentice.dm
code/modules/jobs/job_types/roguetown/youngfolk/squire.dm

Humens can't sign up for their jobs holy...
Fixes a bug?!?!?

Fix the Racial issue

---

code/modules/mob/living/carbon/human/species_types/furry/akula.dm
code/modules/mob/living/carbon/human/species_types/furry/anthromorph.dm
code/modules/mob/living/carbon/human/species_types/furry/anthromorphsmall.dm
code/modules/mob/living/carbon/human/species_types/furry/demihuman.dm
code/modules/mob/living/carbon/human/species_types/furry/dracon.dm
code/modules/mob/living/carbon/human/species_types/furry/kobold.dm
code/modules/mob/living/carbon/human/species_types/furry/lizardfolk.dm
code/modules/mob/living/carbon/human/species_types/furry/lupian.dm
code/modules/mob/living/carbon/human/species_types/furry/tabaxi.dm
code/modules/mob/living/carbon/human/species_types/furry/vulpkanin.dm
code/modules/mob/living/carbon/human/species_types/roguetown/dwarf/dwarfm.dm
code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfd.dm
code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfs.dm
code/modules/mob/living/carbon/human/species_types/roguetown/goblin/goblinp.dm
code/modules/mob/living/carbon/human/species_types/roguetown/human/humen.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/aasimar.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/halfelf.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/halforc.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/tiefling.dm

Completely overhauls the lore of all races in the game.
Lyndvhar lore is good. The single sentence lore of the furtown server's for their races are bad.

Racial Lore Update

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/knighterrant.dm
code/modules/jobs/job_types/roguetown/yeomen/blacksmith.dm

Reduces mage slots to 2 and knight errant to 1. Also fixing blacksmith and adding pick prob to knight errant.
Bowl wants it... and the other stuff is fixes.

Slot reduction and fixes

---

code/__DEFINES/migrants.dm
code/datums/migrants/migrant_waves/heartfelt roles.dm
code/datums/migrants/migrant_waves/heartfelt wave.dm
code/modules/clothing/rogueclothes/armor.dm
code/modules/clothing/rogueclothes/cloaks.dm
code/modules/clothing/rogueclothes/storage.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/heartfelt.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/heartfelthand.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/knighterrant.dm
code/modules/jobs/job_types/roguetown/goblin/chieftain.dm

Changes the Heartfelt wave to a similar wave, but for the Weocilyn barony instead, racelocking and age locking appropriate roles, also racelocking Knight-Errant to every race but monsterous
Ask the host

The Weocilyn Remnants

---

code/datums/gods/patrons/divine_pantheon.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
code/modules/jobs/job_types/roguetown/church/druid.dm
code/modules/spells/roguetown/acolyte/dendor.dm

Ports Druid Shapeshifting for my babe @anything86 😍 💋 
DON'T QUESTION ME....

Ports Druid Shapeshifting

---

code/modules/jobs/job_types/roguetown/youngfolk/servant.dm
code/modules/jobs/job_types/roguetown/youngfolk/shophand.dm

Lets everyone to shophand and lets shunned and up in servant

---

code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/herald.dm
lyndvhar.dme

Title ### **IF YOU WANT RACIAL CHANGES LET ME KNOW**
More fun

Ports the Herald Towner Class

---

code/__DEFINES/say.dm
code/__HELPERS/text.dm
code/controllers/subsystem/job.dm
code/modules/admin/verbs/schizohelp.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/jobs/job_types/_job.dm
code/modules/mob/dead/new_player/preferences_setup.dm
code/modules/mob/living/carbon/human/human_defines.dm
code/modules/mob/living/carbon/human/human_topic.dm
code/modules/mob/living/simple_animal/rogue/creacher/cat.dm
code/modules/mob/say.dm
code/modules/spells/roguetown/acolyte/dendor.dm
lyndvhar.dme

Commit names + title
MORE AZURE FREEK

Preferences port + fix for dendor catform + virtue/vice job restrictions

---

_maps/map_files/lyndvhar_city/lyndvhar_city.dmm

AriaMappingFixes4

---

code/__HELPERS/config.dm
code/controllers/globals.dm
code/modules/admin/admin.dm
code/modules/admin/admin_verbs.dm
code/modules/admin/verbs/toggle_looc.dm
modular_hearthstone/code/interface/LOOC.dm

What it says on the tin
Idk bowl told me to

Adds an admin toggle for OOC

---

code/modules/mob/dead/new_player/sprite_accessory/hair.dm

changes gronn braid to rhaenvalian braid (this is partially a devlog test)

---

code/controllers/globals.dm
code/modules/admin/admin.dm
code/modules/admin/admin_verbs.dm
code/modules/admin/verbs/toggle_looc.dm

This KILLS the server
Need it for public launch + updates

This adds a button to execute the server

---

code/game/gamemodes/roguetown/roguetown.dm
code/modules/jobs/job_types/roguetown/adventurer/bandit.dm

Fixes bandit slots, adjusts chances for antags

---

_maps/map_files/lyndvhar_city/lyndvhar_city.dmm

ManorDoorFix

---

code/modules/client/preferences.dm

Headshots are back, rejoice

---

code/_onclick/click.dm
code/modules/mob/living/carbon/rogfatstam.dm

Reduces stamina recovery interval, increases impact of athletics on stamina, makes attacking not stagger your stamina recovery.
People were complaining about not enough stamina.

Quick Stamina Patch

---

code/modules/mob/living/say.dm
code/modules/mob/say.dm

Now when players /emphasize/ their speech it will be properly formatted with some neat regex
(port over of: https://github.com/sylphynford/Penumbra/pull/110)
You can now use +text+ to bold, and nest it, e.g.
/this text is italics +with some bold text nested inside,+ isn't that neat?/

Updates Say.dm

---

code/game/objects/items/rogueitems/hair_dye.dm
code/game/objects/items/rogueweapons/melee/knives.dm
code/modules/cargo/packsrogue/apparel.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/towndoctor.dm
code/modules/roguetown/roguecrafting/items.dm
lyndvhar.dme

Adds hairstyles to scissors, hairdyes and gives barber surgeons scissors and dyes
Ability to change your haircut/hair color in-game

Ports scissors and hair dye

---

code/datums/sexcon/sexcon.dm
code/datums/sexcon/sexcon_reagents.dm
code/modules/mob/living/carbon/carbon_defense.dm
code/modules/mob/living/carbon/human/life.dm

So it seems every good thing must come to an end... Despite widespread acclaim, it appears not everyone was in agreement with the combination of Azure groin descriptors and handholding raising arousal up to the hard-on threshold. Farewell, turgid and leaky prisoners.
Jokes aside, this locks it behind a certain condition which should have been in place to begin with. I also hereby swear to stop touching sexcon since this has clearly creeped in scope.
Stops people from getting aroused from getting grabbed. Yeah.

DISABLES Handholding

---

code/modules/cargo/packsrogue/luxury.dm
code/modules/roguetown/roguecrafting/alchemy.dm

No More Riddler

---

code/modules/mob/living/say.dm

Formating is back yayyyyy

---

code/modules/jobs/job_types/roguetown/nobility/lady.dm
code/modules/jobs/job_types/roguetown/nobility/lord.dm
code/modules/jobs/job_types/roguetown/youngfolk/prince.dm

you owe me a blowjob
Adds half-kin to Viscount, Consort, and Heirs.
I think it would be quite humorous to have rulers that people are discriminatory against and the conflict that could stem from them trying to hold power against a group of people that REALLY don't like them is funny. Also the people begging me made me feel some pity for them.

The individual known as "another an mouse" on my Discord owes me a rabbit family.

---

_maps/map_files/lyndvhar_city/lyndvhar_city.dmm

i fucked up their spawn
this unfucks it

barkeeper spawn fix

---

code/__DEFINES/traits.dm
code/__HELPERS/unsorted.dm
code/datums/mob_descriptors/descriptors/body.dm
code/datums/mob_descriptors/descriptors/face.dm
code/datums/mob_descriptors/descriptors/height.dm
code/datums/mob_descriptors/descriptors/stature.dm
code/modules/client/descriptors/descriptor_choice.dm
code/modules/clothing/rogueclothes/neck.dm
code/modules/mob/inventory.dm
code/modules/mob/living/carbon/human/emote.dm
code/modules/mob/living/grabbing.dm
code/modules/mob/living/living.dm
code/modules/mob/mob.dm

As it says on the tin. Most of these are from Ratwood, also includes a helper proc for creating skill-based timers.
Bugfix good. Also adds much needed variety and option to the descriptors with flavor text gone.

Assorted Ported Bugfixes and Some New Descriptors

---

code/modules/jobs/job_types/roguetown/adventurer/adventurer.dm

Lowers adventurers from 20 to 10.
More focus on the city. After all- the roads are almost inhospitable currently.. why would anyone want to travel these roads?
But no, really. More focus on the city and the people within is good. Antagonism should come from threats within more than threats outside- changes it up a little.

Slashes Adventurers in half and renames them

---

code/modules/mob/living/carbon/human/species_types/roguetown/other/werewolf.dm

Sprays and Neuters the Vulfs
I feel like this should go without saying,

Fixes Issue #97

---

strings/russian_replacement.json

Totally removes the Cyrillic, adds a couple word replacements
Unsurprisingly, the letter replacements didn't play well with runechat and ended up being incomprehensible and often not displaying.

Redoes the Russian Accent 

---

code/game/gamemodes/roguetown/chaosmode.dm
code/game/objects/effects/landmarks.dm
code/modules/admin/verbs/randomverbs.dm
code/modules/jobs/job_types/_job.dm
code/modules/jobs/jobs.dm

Maybe??
Fixes outlander not being selectable as a latejoin? Maybe?
So people can actually play the job.

Fixes Outlander maybe?

---

code/modules/spells/spell_types/shapeshift.dm

You no longer see someones name while they are shapeshifted
Something something stealth, done at the request of a player

Nameless Shapeshifting

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm

Lets fighter actually spawn with their spear.

All this does is fix a bug

---

code/modules/spells/roguetown/confessor.dm

Mfw
Severely nerfs the range, removed the weird aura and replaces it with an FOV, also fixes mage checks.. I think?

Psydonian Nun Fixes

---

code/game/objects/items/rogueitems/magic.dm

The scrying orb is now impossible to get, court magi should be able to keep theirs. Still has a chance to break below Master Arcayne though
Above

Scrying Orb Stat changes

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/anthrax.dm

Totally forgot to test other races trying to do it, 
Bugs bad

Anthraxi Hotfix

---

modular_azurepeak/virtues/items.dm

ArsonistVirtueFix

---

code/modules/clothing/rogueclothes/armor.dm
code/modules/clothing/rogueclothes/mask.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/anthrax.dm

Adjusts lore slightly away from where it was ported.
Don't need confusing lore from other servers (Stonekeep in this instance) intermixing here and just making people confused.

Anthraxi lore update

---

code/modules/mob/living/grabbing.dm

ports the graggarite blood drinking pr from Azure
increases total amount of blood sucked per click by everyone
lets graggarites drink blood from players without vomiting 
also gives them a little hydration for each sip
uhmm... they like. eat raw meat and stuff, why can't they drink blood from people?

lets graggarites drink blood from players without puking

---

code/__DEFINES/flags.dm
code/__DEFINES/mobs.dm
code/datums/keybinding/living.dm
code/game/atoms.dm
code/game/atoms_movable.dm
code/game/turfs/closed/_closed.dm
code/modules/mob/living/carbon/update_icons.dm
code/modules/mob/living/living.dm
code/modules/mob/living/living_defines.dm
code/modules/mob/living/living_movement.dm
code/modules/mob/mob.dm
code/modules/mob/mob_defines.dm
code/modules/mob/mob_movement.dm
code/modules/pixel_shift/pixel_shifting.dm
lyndvhar.dme

ports the azure pixel shift pr, along with its subsequent bug-fix
Automatically bound to the B key
https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/1868
https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/1881
better pixel shifting is always more entertaining.

Ports Azures better pixelshifting

---

_maps/map_files/generic/CentCom.dmm
code/game/objects/structures/fluff.dm
code/modules/roguetown/roguemachine/hoardmaster.dm

Changing the layout of the camp to make it more like a camp surrounding an idol and a shrine rather than just a big building sitting in the woods.
Uniqueness good. New designs good.

Editing the bandit camp

---

code/game/objects/structures/roguewindow.dm

lets you pry open windows with daggers
more thievery and such

lets you pry open windows with daggers

---

code/__DEFINES/misc.dm

This PR is causing an issue with sidesprites.

Revert "Update misc.dm"

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/hoplite.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/knighterrant.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/trader.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
code/modules/jobs/job_types/roguetown/adventurer/wretch.dm

Does some minor nitpick work to Outlander gear and some of their skills to bring down equipment quality.
This should incentivize these groups of people going more to places like the tailor and the smithy for equipment- therefore forcing them to interact with the city at large. It also brings their gear down to the level of what would be in the town as seen in the Garrison skill/equipment rework.

Outlander Gear and Skill Adjustments

---

_maps/map_files/dun_manor/dun_manor.dmm
_maps/map_files/lyndvhar_city/lyndvhar_city.dmm
code/game/gamemodes/objective_items.dm
code/game/gamemodes/roguetown/chaosmode.dm
code/game/gamemodes/roguetown/roguetown.dm
code/game/objects/effects/landmarks.dm
code/game/objects/items/rogueitems/keys.dm
code/modules/client/preferences.dm
code/modules/jobs/job_types/roguetown/nobility/captain.dm
code/modules/jobs/job_types/roguetown/nobility/knight.dm
code/modules/jobs/job_types/roguetown/nobility/marshal.dm
code/modules/jobs/jobs.dm
code/modules/mob/living/carbon/human/death.dm
code/modules/roguetown/roguemachine/scomm.dm
modular_hearthstone/code/game/objects/items/signal_horn.dm

Adjusts the gear of the knights to be less heavily steel-focused. It's not as MUCH as the others, as these are meant to be the most prestigious fighting figures in the city. They are a last line of defense against the almighty, and are more than likely only going to be guarding the nobles- barring the captain.
This PR also renames them as I didn't really like their names.
Adjusting gear quality values as per all the other PRs. Obviously some of this could use some touch-up, but it's a step in the right direction, I feel.

Noble Retinue of the Viscount

---

code/__DEFINES/roguetown.dm
code/game/objects/effects/landmarks.dm
code/modules/jobs/job_types/roguetown/peasants/bathmaid.dm
code/modules/jobs/jobs.dm
code/modules/roguetown/roguemachine/bathmaster.dm

Too long of a name for a job so simple.
Less.. paragraph bloating. It doesn't need to be /this/ complex for the baths of all places.

Changes the name of the Bathhouse Attendant

---

code/__DEFINES/traits.dm
code/_compile_options.dm
code/game/objects/structures/walldeco.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/Iconoclast.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/brigand.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/knave.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/sawbones.dm
code/modules/mob/living/carbon/human/examine.dm

fixes bandit poster examine not working, the excidium does NOT work for bandits atm
being able to identify bandits is good

fixes the bandit poster examine

---

code/datums/migrants/migrant_wave.dm
code/modules/jobs/job_types/roguetown/adventurer/bandit.dm

Reverts LYNDVHAR-NOBILITY/Lyndvhar#249
fucking broke something...

Revert "Re-enables the bandit wave (one of them, atleast)"

---

code/modules/mob/living/living.dm

As requested by discord user eugshev. This change aims to make the game more friendly and inclusive to all audiences.
I don't know.

Direct Commit Post-round Nerf Balancejak

---

code/game/objects/items/rogueweapons/melee/flail.dm

whips shouldnt embed
silly whips getting stuck in people

removes embeds from whips

---

_maps/map_files/lyndvhar_city/lyndvhar_city.dmm
code/modules/jobs/job_types/roguetown/garrison/veteran.dm

Fixed Version of https://github.com/LYNDVHAR-NOBILITY/Lyndvhar/pull/259

VeteranTweaks2

---

_maps/map_files/lyndvhar_city/lyndvhar_city.dmm

Veteran house moved near the soilsons. Fuck u bowl

VeteranHouseFix

---

_maps/map_files/lyndvhar_city/lyndvhar_city.dmm
code/modules/jobs/job_types/roguetown/mercenaries/classes/atgervi.dm
modular_azurepeak/code/datums/loadout.dm

Fixes the stairs that lead to nowhere near the church. 
Fixes the atgervi merc class forcing you to have an inhumen patron. 
Fixes the path to the cowbell collar in the loadout menu. 
Adds the catbell collar to the loadout menu.

SmallFixes1

---

code/modules/jobs/job_types/roguetown/youngfolk/squire.dm

Irregular Squire has level 2 Sneaking
Makes very little sense to me that allegedly the job being trained to be a Skirmisher... Can't sneak? Like ambushing is probably the most important part of being semi-modern professional Light Infantry.

Irregular Scout has level 2 sneaking

---

code/datums/gods/faiths/atheism.dm
code/datums/gods/patrons/atheism.dm
code/game/objects/items/rogueitems/inquisitionrelics.dm

TMC This I beg you. There's probably some stupid niche interaction that MIGHT break from this or something. I doubt it but who the heck knows at this point.
Anyways adds apostasy 100% because not because I play Grenzer and want to do the full larp. This faith does basically nothing beyond just make you godless.
Some blurb and larp changes are included.
Bowl mentioned there's populations which follow no God. This is so you can roleplay them.

You can now pick Apostasy

---

_maps/map_files/lyndvhar_city/lyndvhar_city.dmm

Oh you know just some.. edits to the map and stuff.. I wouldn't read the fine print though..
Find Out In Game

some.. "map edits"

---

strings/middlespeak.json

These break the byond chat. Who even made these? BYOND does NOT like letters like these.
Unbreaks the language.

Removes runespeak from Middle

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/ranger.dm

Adds a new subclass to ranger based on survival and slings.

SurvivalistRangerSubclass

---

code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/blacksmith.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/carpenter.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/cheesemaker.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/fisher.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/hunter.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/miner.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/peasant.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/seamstress.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/tbutcher.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/towndoctor.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/witch.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/woodcutter.dm

PilgrimOutlanderMerge

---

_maps/map_files/lyndvhar_city/lyndvhar_city.dmm

Wipes out the Great Furnace. It was only a placeholder anyways.
Steel not being instantly available roundstart is the entire point on why everyone is starting with iron crap. Either find a riddle or smelt down steel equipment you do find to get steel.

malum fucking weeps

---

code/modules/jobs/job_types/roguetown/nobility/captain.dm
code/modules/jobs/job_types/roguetown/nobility/knight.dm

Title drops Retinue jobs with 3 climbing down to 2.
Yeah. This is almost definitely gonna be contentious but this is my reasoning for doing this in bulletpoint format:
- Both of these jobs are intended to be the 'Riding' jobs which mean they're probably on Saiga's and thus probably faster than you. They shouldn't also be able to climb better than you which is why I see most people pick these over the other jobs which I think is bad design.
- Knights should have worse mobility to curtail their insane killing power compared to literally everyone else. I think the irregular duelist is also somewhat problematic with 4 climbing because you're basically a regular speed build with expert swords and some bonus stats over other folk. It's main difference over other catas is if you want to use …

Drops cav captain and cav cata to 2 climbing

---

_maps/map_files/lyndvhar_city/lyndvhar_city.dmm

Got bored. Decided the smithy quarter was a bit too big. Made it more compact. Adjusted the artificer's a bit more. Made them poorer too. Everyone gets made poor.
Poor good. Shitty lifestyle fun. Zero to hero.

Blacksmithing Quarter remap

---

code/modules/cargo/packsrogue/Knight.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/hedgeknight.dm

Bowl ~~speed~~merged my pr but here's some more touchups for the Hedge Cataphract
Loadout/Stat wise
- Swapped the Bastard for an old sword to make the onspawn loadout mildly worse if you're doing shields to encourage you to buy a new sword.
- You now get steel knuckles on spawn instead of a knife so you have some kind of less than lethal option. ~~and its a cooler secondary for a hedge knight imo but w/e~~
- Dropped their Per stat by 1
Favor menu buy wise
- The stupid frog helmet is 25 favor from 60 since the FOV actually makes it so bad that I've decided its your cheapo helmet. Get it if you really want to flex that budget full face coverage option.
- Iron/Steel plate are up by 20 because I saw them roll insanely low on some of my local hosts.
- Fluted is up from 100 to 125 for the same …

Hedgeknight the hedgecutter

---

_maps/map_files/lyndvhar_city/lyndvhar_city.dmm

Bath-house remap with the new sprites! yippee!

BathHousePart2

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm

Spawns with a hunting knife.
Has 3 athletics rather than 2.
Gives you journeyman athletics and a knife when you spawn in.

Spellblade touches

---

code/modules/jobs/job_types/roguetown/Inquisition/inquisitor.dm
code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/psydonianmonk.dm
code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/psydoniantemplar.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/ranger.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
code/modules/jobs/job_types/roguetown/courtier/councillor.dm
code/modules/jobs/job_types/roguetown/garrison/villagechief.dm
code/modules/jobs/job_types/roguetown/nobility/marshal.dm
code/modules/jobs/job_types/roguetown/nobility/steward.dm
code/modules/jobs/job_types/roguetown/yeomen/merchant.dm
code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
code/modules/jobs/job_types/roguetown/youngfolk/servant.dm
code/modules/mob/mob_helpers.dm

Adjustments to certain classes (both balancing and attire formatting). This ALSO begins to slowly chip away at removing certain combat tracks (it also gets rid of some of the god-awful ones). I'll be doing a later PR that is going to completely re-organize the music files into actual folders representing which relative area they are supposed to represent (guards in garrison folder etc).
Not in this PR, though.
Because I said so.

Adventurer adjustment number 500000

---

code/modules/roguetown/roguecrafting/alchemy/reagents.dm

4am mjp strikes again

---

code/game/objects/items/rogueweapons/melee/axes.dm

Title
Broken things are NOT nice.

Graggar Axe QuickFix
